---
- name: Upload static website to primary bucket
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Clone the website repository
      ansible.builtin.git:
        repo: git@github.com:open-shaiya/www.archive.openshaiya.org.git
        dest: ./openshaiya_archive/

    - name: Upload the website to the s3 bucket
      community.aws.s3_sync:
        bucket: "{{ archive_bucket }}"
        file_root: ./openshaiya_archive/www/